import type { FieldCheckDefinition } from "./investigationTypes";

export const MEDICAL_SITE_LOCAL_CHECKS: FieldCheckDefinition[] = [
  {
    id: "medical-open",
    category: "medical",
    label: "施設の現在の営業状況を確認",
    reason: "P04 2020は現在の営業を保証しないため。",
    origin: "data_gap",
    sourceGapIds: ["facility_availability"],
    defaultPriority: "high",
  },
  {
    id: "medical-service",
    category: "medical",
    label: "診療科・サービス種別を確認",
    reason: "施設位置だけでは必要なサービスがあるか分からないため。",
    origin: "data_gap",
    sourceGapIds: ["facility_availability"],
    defaultPriority: "high",
  },
  {
    id: "medical-eligibility",
    category: "medical",
    label: "利用条件・予約・受入条件を確認",
    reason: "公開施設情報に現在の受入条件が含まれないため。",
    origin: "data_gap",
    sourceGapIds: ["facility_availability"],
    defaultPriority: "high",
  },
  {
    id: "medical-shuttle",
    category: "medical",
    label: "施設送迎の有無と利用条件を確認",
    reason: "施設送迎はP04・P11の収録範囲外であるため。",
    origin: "data_gap",
    sourceGapIds: ["facility_availability", "gtfs"],
    defaultPriority: "medium",
  },
  {
    id: "medical-capacity",
    category: "medical",
    label: "対象日時の受入可否を確認",
    reason: "距離は受入能力や到達可能性を意味しないため。",
    origin: "analysis_assumption",
    sourceGapIds: ["facility_availability"],
    defaultPriority: "high",
  },
  {
    id: "site-land",
    category: "site",
    label: "確認地点の用地・境界を確認",
    reason: "PLATEAU道路面上の点は用地候補や設置可能性を意味しないため。",
    origin: "analysis_assumption",
    sourceGapIds: [],
    defaultPriority: "medium",
  },
  {
    id: "site-road-safety",
    category: "site",
    label: "道路安全と見通しを確認",
    reason: "道路形状だけでは停車・乗降時の安全性を判断できないため。",
    origin: "plateau_context",
    sourceGapIds: ["walking_network"],
    defaultPriority: "high",
  },
  {
    id: "site-stop",
    category: "site",
    label: "車両が停車・転回できるか確認",
    reason: "仮想地点比較は運行・停車可能性を検証していないため。",
    origin: "analysis_assumption",
    sourceGapIds: [],
    defaultPriority: "high",
  },
  {
    id: "site-existing",
    category: "site",
    label: "周辺の既存施設と利用可能設備を確認",
    reason: "公開データに未収録の施設や運用があり得るため。",
    origin: "data_gap",
    sourceGapIds: ["local_services"],
    defaultPriority: "medium",
  },
  {
    id: "site-owner",
    category: "site",
    label: "管理主体と協議先を確認",
    reason: "公開空間形状だけでは管理・占用関係を判断できないため。",
    origin: "analysis_assumption",
    sourceGapIds: [],
    defaultPriority: "medium",
  },
  {
    id: "site-operator",
    category: "site",
    label: "交通事業者との協議事項を整理",
    reason: "CITY GAPは運行計画や事業者合意を決定しないため。",
    origin: "analysis_assumption",
    sourceGapIds: [],
    defaultPriority: "medium",
  },
  {
    id: "local-association",
    category: "local",
    label: "自治会・地域交通の既存取組を確認",
    reason: "地域内の自主運行は公開データだけでは把握できないため。",
    origin: "data_gap",
    sourceGapIds: ["local_services"],
    defaultPriority: "high",
  },
  {
    id: "local-destination",
    category: "local",
    label: "住民の実際の移動先を確認",
    reason: "最寄り施設が実際の利用先とは限らないため。",
    origin: "data_gap",
    sourceGapIds: ["local_services", "facility_availability"],
    defaultPriority: "high",
  },
  {
    id: "local-time",
    category: "local",
    label: "移動が集中する曜日・時間帯を確認",
    reason: "500m人口と施設位置には利用時間が含まれないため。",
    origin: "data_gap",
    sourceGapIds: ["local_services", "gtfs"],
    defaultPriority: "medium",
  },
  {
    id: "local-season",
    category: "local",
    label: "季節による移動・通行条件の変化を確認",
    reason: "公開データは季節変動を表さないため。",
    origin: "data_gap",
    sourceGapIds: ["local_services", "walking_network"],
    defaultPriority: "medium",
  },
  {
    id: "local-recognition",
    category: "local",
    label: "地域で認識されている課題と既存施策を確認",
    reason: "分析候補は地域課題の認定や政策優先順位ではないため。",
    origin: "analysis_assumption",
    sourceGapIds: ["local_services"],
    defaultPriority: "high",
  },
];
