import type { FieldCheckDefinition } from "./investigationTypes";

export const TRANSPORT_WALKING_CHECKS: FieldCheckDefinition[] = [
  {
    id: "transport-stop",
    category: "transport",
    label: "収録されたバス停・駅が現在も実際に利用可能か",
    reason: "P11は収録時点の位置情報で、現在の利用可否を保証しないため。",
    origin: "data_gap",
    sourceGapIds: ["gtfs"],
    defaultPriority: "high",
  },
  {
    id: "transport-frequency",
    category: "transport",
    label: "運行頻度を確認",
    reason: "P11には運行本数が含まれないため。",
    origin: "data_gap",
    sourceGapIds: ["gtfs"],
    defaultPriority: "high",
  },
  {
    id: "transport-hours",
    category: "transport",
    label: "運行曜日・始発・終発を確認",
    reason: "P11には曜日・時間が含まれないため。",
    origin: "data_gap",
    sourceGapIds: ["gtfs"],
    defaultPriority: "high",
  },
  {
    id: "transport-demand",
    category: "transport",
    label: "デマンド交通の運行区域と利用条件を確認",
    reason: "収録停留所だけでは地域のデマンド交通を把握できないため。",
    origin: "data_gap",
    sourceGapIds: ["gtfs", "local_services"],
    defaultPriority: "medium",
  },
  {
    id: "transport-shuttle",
    category: "transport",
    label: "既存送迎サービスを確認",
    reason: "施設・地域による送迎はP11に含まれないため。",
    origin: "data_gap",
    sourceGapIds: ["gtfs", "local_services"],
    defaultPriority: "medium",
  },
  {
    id: "walking-passability",
    category: "walking",
    label: "道路を実際に歩いて通行できるか",
    reason: "PLATEAU道路面は歩行可能性を表さないため。",
    origin: "data_gap",
    sourceGapIds: ["walking_network"],
    defaultPriority: "high",
  },
  {
    id: "walking-sidewalk",
    category: "walking",
    label: "歩道の有無と有効幅員を確認",
    reason: "公式歩行ネットワークと歩道属性を収録していないため。",
    origin: "data_gap",
    sourceGapIds: ["walking_network"],
    defaultPriority: "high",
  },
  {
    id: "walking-crossing",
    category: "walking",
    label: "横断箇所と横断時の見通しを確認",
    reason: "道路形状だけでは安全な横断可否を判断できないため。",
    origin: "data_gap",
    sourceGapIds: ["walking_network"],
    defaultPriority: "high",
  },
  {
    id: "walking-step",
    category: "walking",
    label: "段差・縁石・路面状態を確認",
    reason: "PLATEAU形状から現地の細かな段差を確認できないため。",
    origin: "data_gap",
    sourceGapIds: ["walking_network"],
    defaultPriority: "medium",
  },
  {
    id: "walking-slope",
    category: "walking",
    label: "坂の連続性と歩行負担を確認",
    reason: "DEMは地形文脈であり、歩行経路上の測量勾配ではないため。",
    origin: "plateau_context",
    sourceGapIds: ["walking_network"],
    defaultPriority: "high",
  },
  {
    id: "walking-weather",
    category: "walking",
    label: "冬季・雨天時の通行条件を確認",
    reason: "公開データは季節・悪天候時の路面状態を表さないため。",
    origin: "data_gap",
    sourceGapIds: ["walking_network", "local_services"],
    defaultPriority: "medium",
  },
  {
    id: "walking-building-link",
    category: "walking",
    label: "住宅建物から道路までの接続を確認",
    reason: "建物形状と道路形状だけでは入口・私道・階段を特定できないため。",
    origin: "plateau_context",
    sourceGapIds: ["walking_network"],
    defaultPriority: "high",
  },
];
